name: Setup infraestructure and push docker img to Artifact Registry

on:
  push:
    branches:
      - master
      - dev

env:
  API_IMAGE_NAME: example-api
  CLIENT_IMAGE_NAME: example-client
  IMAGES_FOLDER: images

jobs:
  provision_infraestructure:
    name: provision app infraestructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup Terraform Backend
        id: backend
        run: |
          cat > backend.tf << EOF
          terraform {
            backend "gcs" {
              bucket = "${{ secrets.GCS_BUCKET_NAME }}"
              prefix = "terraform/state"
            }
          }
          EOF

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          # these TF_VAR_<var_name> can be accessed on terraform by var.<var name>
          # (e.g.: TF_VAR_project can be accessed on main.tf as var.project)
          TF_VAR_project: ${{ secrets.TF_VAR_project }}
          TF_VAR_region: ${{ secrets.TF_VAR_region }}
          TF_VAR_zone: ${{ secrets.TF_VAR_zone }}
          TF_VAR_repository_name: ${{ env.IMAGES_FOLDER }}
          TF_VAR_bucket_name: ${{ secrets.GCS_BUCKET_NAME }}
          TF_VAR_bucket_location: ${{ secrets.GCS_BUCKET_LOCATION }}

      - name: Terraform Format
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_project: ${{ secrets.TF_VAR_project }}
          TF_VAR_region: ${{ secrets.TF_VAR_region }}
          TF_VAR_zone: ${{ secrets.TF_VAR_zone }}
          TF_VAR_repository_name: ${{ env.IMAGES_FOLDER }}
          TF_VAR_bucket_name: ${{ secrets.GCS_BUCKET_NAME }}
          TF_VAR_bucket_location: ${{ secrets.GCS_BUCKET_LOCATION }}

  push_containers_to_artifact_registry:
    name: push containers to artifact registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker Client
        run: gcloud auth configure-docker us-east1-docker.pkg.dev #without setting up configure docker for the specific region that you want to deploy the image, both artifact registry and cloud run throw authentication errors even with the auth@v1 action

      - name: Build API Docker Image
        run: docker build -t $API_IMAGE_NAME:latest ./src/api

      - name: Push API Docker Image to Artifact Registry
        env:
          GIT_TAG: v0.1.0
        run: |-
          docker tag $API_IMAGE_NAME:latest us-east1-docker.pkg.dev/${{secrets.TF_VAR_project}}/$IMAGES_FOLDER/$API_IMAGE_NAME:latest 
          docker tag $API_IMAGE_NAME:latest us-east1-docker.pkg.dev/${{secrets.TF_VAR_project}}/$IMAGES_FOLDER/$API_IMAGE_NAME:$GIT_TAG
          docker push us-east1-docker.pkg.dev/${{secrets.TF_VAR_project}}/$IMAGES_FOLDER/$API_IMAGE_NAME:latest
          docker push us-east1-docker.pkg.dev/${{secrets.TF_VAR_project}}/$IMAGES_FOLDER/$API_IMAGE_NAME:$GIT_TAG

      - name: Build Client Docker Image
        run: docker build -t $CLIENT_IMAGE_NAME:latest ./src/client

      - name: Push Client Docker Image to Artifact Registry
        env:
          GIT_TAG: v0.1.0
        run: |-
          docker tag $CLIENT_IMAGE_NAME:latest us-east1-docker.pkg.dev/${{secrets.TF_VAR_project}}/$IMAGES_FOLDER/$CLIENT_IMAGE_NAME:latest 
          docker tag $CLIENT_IMAGE_NAME:latest us-east1-docker.pkg.dev/${{secrets.TF_VAR_project}}/$IMAGES_FOLDER/$CLIENT_IMAGE_NAME:$GIT_TAG
          docker push us-east1-docker.pkg.dev/${{secrets.TF_VAR_project}}/$IMAGES_FOLDER/$CLIENT_IMAGE_NAME:latest
          docker push us-east1-docker.pkg.dev/${{secrets.TF_VAR_project}}/$IMAGES_FOLDER/$CLIENT_IMAGE_NAME:$GIT_TAG


  publish_API_container_to_cloud_run:
    needs: push_containers_to_artifacy_registry
    name: build container and push to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Configure Docker Client
        run: gcloud auth configure-docker us-east1-docker.pkg.dev #without setting up configure docker for the specific region that you want to deploy the image, both artifact registry and cloud run throw authentication errors even with the auth@v1 action

      - name: Deploy API image to Cloud Run
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: ${{ env.API_IMAGE_NAME }}
          image: us-east1-docker.pkg.dev/${{secrets.TF_VAR_project}}/${{ env.IMAGES_FOLDER }}/${{ env.API_IMAGE_NAME }}:latest
          env_vars: |
            PORT=8080

  publish_Client_container_to_cloud_run:
    needs: push_containers_to_artifacy_registry
    name: build container and push to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Get Cloud Run API Service URL
        id: get_service_url
        run: |
          service_name=$API_IMAGE_NAME
          service_url=$(gcloud run services describe "$API_IMAGE_NAME" --format "value(status.url)")
          echo "::set-output name=service_url::$service_url"

      - name: Configure Docker Client
        run: gcloud auth configure-docker us-east1-docker.pkg.dev #without setting up configure docker for the specific region that you want to deploy the image, both artifact registry and cloud run throw authentication errors even with the auth@v1 action

      - name: Deploy Client image to Cloud Run
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: ${{ env.CLIENT_IMAGE_NAME }}
          image: us-east1-docker.pkg.dev/${{secrets.TF_VAR_project}}/${{ env.IMAGES_FOLDER }}/${{ env.CLIENT_IMAGE_NAME }}:latest
          env_vars: |
            PORT=8080
            API_URL=${{ steps.get_service_url.outputs.service_url }}
